[package]
name = "icy-launcher"
version = "0.3.0"
edition = "2021"
authors = ["Manuel Quarneti <hi@mq1.eu>"]
repository = "https://github.com/mq1/icy-launcher"
license = "GPL-3.0-only"
description = "An unofficial launcher for Minecraft: Java Edition"

[dependencies]
iced = { version = "0.9", features = ["image", "svg"] }
iced_aw = { version = "0.5", features = ["wrap", "floating_element", "spinner"] }
rfd = "0.11"
ureq = { version = "2.6", features = ["json"] }
open = "4.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
directories = "5.0"
once_cell = "1.17"
time = { version = "0.3", features = ["serde"] }
oauth2 = { version = "4.3", default-features = false, features = ["ureq"] }
copypasta = "0.8"
version-compare = "0.1"
mlua = { version = "0.8", features = ["lua54", "vendored", "serialize"] }
flate2 = "1.0"
tar = "0.4"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
phf = { version = "0.11", features = ["macros"] }
sha1 = "0.10"
sha2 = "0.10"
digest = "0.10"
base16ct = { version = "0.2", features = ["alloc"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
