[package]
name = "ice-launcher"
version = "0.0.18+dev"
edition = "2021"
authors = ["Manuel Quarneti <hi@mq1.eu>"]
repository = "https://github.com/mq1/ice-launcher"
license = "GPL-3.0-only"
description = "An unofficial launcher for Minecraft: Java Edition"

[package.metadata.bundle]
name = "Ice Launcher"
identifier = "eu.mq1.ice-launcher"
icon = ["ice-launcher.png"]
copyright = "Copyright (C) 2022 Manuel Quarneti"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", rev = "65cc1f6b5e2d2203e6e8f2766e584c3bc8b67edb", features = ["im", "image", "png"] }
isahc = { version = "1", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2", features = ["serde"] }
const_format = "0.2"
color-eyre = "0.6"
open = "2"
directories = "4"
strum = "0.24"
strum_macros = "0.24"
toml = "0.5"
once_cell = "1"
rand = "0.8"
sha2 = "0.10"
base64-url = "1"
tiny_http = "0.11"

[target.'cfg(target_os = "windows")'.dependencies]
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
flate2 = "1"
tar = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.package.backtrace]
opt-level = 3
