[package]
name = "ice-launcher"
version = "0.1.2"
edition = "2021"
authors = ["Manuel Quarneti <hi@mq1.eu>"]
repository = "https://github.com/mq1/ice-launcher"
license = "GPL-3.0-only"
description = "An unofficial launcher for Minecraft: Java Edition"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", features = ["im", "image", "png", "serde"] }
tokio = { version = "1", features = ["rt", "macros", "process", "io-util", "fs"] }
async-trait = "0.1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "stream"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2", features = ["serde"] }
color-eyre = "0.6"
open = "2"
directories = "4"
strum = "0.24"
strum_macros = "0.24"
toml = "0.5"
once_cell = "1"
version-compare = "0.1"
sha1 = "0.10"
sha2 = "0.10"
base16ct = { version = "0.1", features = ["alloc"] }
oauth2 = "4"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
flate2 = "1"
tar = "0.4"
tempfile = "3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.package.backtrace]
opt-level = 3
