name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-apple-darwin --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-apple-darwin --release
      - run: |
          lipo target/x86_64-apple-darwin/release/crab-launcher target/aarch64-apple-darwin/release/crab-launcher -create -output "macos/CrabLauncher.app/Contents/MacOS/CrabLauncher"
          ln -s /Applications macos/Applications
          hdiutil create CrabLauncher-${{github.ref_name}}-macos-universal.dmg -volname CrabLauncher -fs HFS+ -srcfolder macos -format UDZO
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-macos-universal.dmg
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          mv target/release/crab-launcher CrabLauncher
          tar czf CrabLauncher-${{github.ref_name}}-linux-x86_64.tar.gz CrabLauncher
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-linux-x86_64.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          Move-Item ./target/release/crab-launcher.exe ./CrabLauncher.exe
          Compress-Archive ./CrabLauncher.exe ./CrabLauncher-${{github.ref_name}}-windows-x86_64.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-windows-x86_64.zip
