name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          cargo build --release --target=aarch64-apple-darwin
          mv "macos/Ice Launcher.app" "Ice Launcher.app"
          mkdir "Ice Launcher.app/Contents/MacOS"
          lipo target/x86_64-apple-darwin/release/ice-launcher target/aarch64-apple-darwin/release/ice-launcher -create -output "Ice Launcher.app/Contents/MacOS/ice-launcher"
          mkdir "Ice Launcher"
          ln -sf /Applications "Ice Launcher/Applications"
          hdiutil create IceLauncher-${{github.ref_name}}-macos.dmg -volname "Ice Launcher" -fs HFS+ -srcfolder "Ice Launcher" -ov -format ULMO
      - uses: softprops/action-gh-release@v1
        with:
          files: IceLauncher-${{github.ref_name}}-macos.dmg
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y libgtk-3-dev
          cargo build --release
          tar czf IceLauncher-${{github.ref_name}}-linux.tar.gz --directory=target/release ice-launcher
      - uses: softprops/action-gh-release@v1
        with:
          files: IceLauncher-${{github.ref_name}}-linux.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo build --release
          Compress-Archive ./target/release/ice-launcher.exe ./IceLauncher-${{github.ref_name}}-windows.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: IceLauncher-${{github.ref_name}}-windows.zip
