name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin
      - run: ./build-macos.sh ${{github.ref_name}}
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-MacOS-Universal2.dmg

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build --release --bin crab-launcher
          mv target/release/crab-launcher CrabLauncher
          tar czf CrabLauncher-${{github.ref_name}}-linux-x86_64.tar.gz CrabLauncher
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-linux-x86_64.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build --release --bin crab-launcher
          Move-Item ./target/release/crab-launcher.exe ./CrabLauncher.exe
          Compress-Archive ./CrabLauncher.exe ./CrabLauncher-${{github.ref_name}}-windows-x86_64.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: CrabLauncher-${{github.ref_name}}-windows-x86_64.zip
