name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest-xl
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: +nightly --target x86_64-apple-darwin --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: +nightly --target aarch64-apple-darwin --release
      - run: |
          lipo target/x86_64-apple-darwin/release/icy-launcher target/aarch64-apple-darwin/release/icy-launcher -create -output "macos/Icy Launcher.app/Contents/MacOS/icy-launcher"
          hdiutil create IcyLauncher-${{github.ref_name}}-macos.dmg -volname "Icy Launcher" -fs HFS+ -srcfolder macos -format UDZO
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-macos-universal.dmg
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: +nightly --release
      - run: tar czf IcyLauncher-${{github.ref_name}}-linux.tar.gz --directory=target/release icy-launcher
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-linux-x86_64.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: +nightly --release
      - run: Compress-Archive ./target/release/icy-launcher.exe ./IcyLauncher-${{github.ref_name}}-windows.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-windows-x86_64.zip
