name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          cargo build --release --target=aarch64-apple-darwin
          mkdir "macos/Icy Launcher.app/Contents/MacOS"
          lipo target/x86_64-apple-darwin/release/icy-launcher target/aarch64-apple-darwin/release/icy-launcher -create -output "macos/Icy Launcher.app/Contents/MacOS/icy-launcher"
          ln -s /Applications "macos/Applications"
          hdiutil create IcyLauncher-${{github.ref_name}}-macos.dmg -volname "Icy Launcher" -fs HFS+ -srcfolder macos -format UDZO
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-macos.dmg
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get -y update
          sudo apt-get install -y libgtk-3-dev
          cargo build --release
          tar czf IcyLauncher-${{github.ref_name}}-linux.tar.gz --directory=target/release icy-launcher
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-linux.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo build --release
          Compress-Archive ./target/release/icy-launcher.exe ./IcyLauncher-${{github.ref_name}}-windows.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: IcyLauncher-${{github.ref_name}}-windows.zip
