name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          cargo build --release --target=aarch64-apple-darwin
          mv ./target/x86_64-apple-darwin/release/ice-launcher ./IceLauncher-${{github.ref_name}}-macos-x86_64
          mv ./target/aarch64-apple-darwin/release/ice-launcher ./IceLauncher-${{github.ref_name}}-macos-aarch64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            IceLauncher-${{github.ref_name}}-macos-x86_64
            IceLauncher-${{github.ref_name}}-macos-aarch64
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y libgtk-3-dev
          cargo build --release
          mv /target/release/ice-launcher ./IceLauncher-${{github.ref_name}}-linux-x86_64
      - uses: softprops/action-gh-release@v1
        with:
          files: IceLauncher-${{github.ref_name}}-linux-x86_64
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo build --release
          Move-Item -Path ".\target\release\ice-launcher.exe" -Destination ".\IceLauncher-${{github.ref_name}}-windows-x86_64.exe"
      - uses: softprops/action-gh-release@v1
        with:
          files: IceLauncher-${{github.ref_name}}-windows-x86_64.exe
